version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    container_name: pg_container
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: profile_login_app
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/profile_login_app
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules
    working_dir: /app
    command: ["npm", "run", "dev"]

  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  db_data:
